### ISSUE TITLE
geodetic2enu got error "ValueError: -pi/2 <= latitude <= pi/2" in pymap3d/utils.py

### ISSUE THREAD

**Issue by khinggan** [geospace-code/pymap3d#36]
**Describe the bug**
What is your expected output value(s)? 
What program/function are you comparing with?
When I use `geodetic2enu`
```python
import pymap3d as pm
lat0, lon0, alt0 = 4029.25745, 11146.61129, 1165.2
lat, lon, alt = 4028.25746, 11147.61125, 1165.1
e, n, u = pm.geodetic2enu(lat, lon, alt, lat0, lon0, alt0)
print(e, n, u)
```

I got an error like 
> ValueError: -pi/2 <= latitude <= pi/2

Can you help me ?

**Comment by scivision** [comment]
I am not sure what the latitude and longitude units are here. PyMap3D assumes "degrees" where south pole is -90 and north pole is 90 for latitude

**Comment by khinggan** [comment]
Thanks a lot
