### ISSUE TITLE
AttributeError: module 'pymap3d' has no attribute 'eci2aer'

### ISSUE THREAD

**Issue by dongsin-kim** [geospace-code/pymap3d#38]
**Describe the bug**
What is your expected output value(s)? 
What program/function are you comparing with?

Hi, I have been actively used an attribute `eci2aer` of `pymap3d`. However, today I suddenly faces an error when I use the attribute. Am I the only person who see this error: `AttributeError: module 'pymap3d' has no attribute 'eci2aer'` ?

#### How to reproduce the error?

1.  `conda create -n myenv python=3.8`
2.  `conda activate myenv`
3. `pip3 install pymap3d`
3.  `python`
4.  `import pymap3d`
5.  `pymap3d.eci2aer()`

OUTPUT:
`AttributeError: module 'pymap3d' has no attribute 'eci2aer'`

**Comment by scivision** [comment]
The ECI functions require numpy. I didn't make Numpy auto-install because most PyMap3D functions work without Numpy for scalars. this is relevant for real-time / microPython and similar.

so just
```sh
conda install numpy
```
and it should work

**Comment by dongsin-kim** [comment]
Hi @scivision,

Thank you for your swift reply and detailed explanations. Based on your advice, I could solve this issue-! Thank you so much.

Now this issue should be closed.
