### ISSUE TITLE
pymap3d version 2.7.2 from conda-forge has import issues

### ISSUE THREAD

**Issue by obbe79** [geospace-code/pymap3d#47]
When importing:

`import pymap3d as pm`

and invoking:

`pm.vincenty.vdist(lat1, lon1, lat2, lon2)`

raises the exception:

`AttributeError: module 'pymap3d' has no attribute 'vincenty'`

In fact, the imported module will no longer import the vincenty module, breaking code that needed pymap3d.vincenty.vdist
![image](https://user-images.githubusercontent.com/9539719/143719104-f01bca48-1ce4-4dbe-b94b-865e6c5ddd82.png)

This behavior was not present in previous installations of the package.

**Comment by scivision** [comment]
The defaults imports were shortened in pymap3d 2.7.0 to help improve import speed, particularly on embedded systems. The README now reflects this. Thanks!

**Comment by nikoloide** [comment]
Hi, try
`import pymap3d.vincenty`
