### ISSUE TITLE
geodetic2enu type annotations cause false errors in type checking

### ISSUE THREAD

**Issue by randallpittman** [geospace-code/pymap3d#50]
`pymap3d.geodetic2enu` has the following type signature: 
```python
def geodetic2enu(
    lat: ndarray,
    lon: ndarray,
    h: ndarray,
    lat0: ndarray,
    lon0: ndarray,
    h0: ndarray,
    ell: Ellipsoid = None,
    deg: bool = True,
) -> tuple[ndarray, ndarray, ndarray]:
    ...
```
I'm pretty sure `lat0`, `lon0`, and `h0` must always be scalars.  If I provide scalar `float` or `int` to these args I get type checking errors.  Furthermore, `lat`, `lon`, and `h` _may_ be either scalar or n-dimensional. If all these args are scalars, the function returns a tuple of three `float`s, not three `ndarray`s.

Admittedly numpy and type checking are a tricky business, so it may be better to only annotate non-numeric stuff. Alternatively, consider looking into `numpy.typing` and `ArrayLike`.

I think this probably applies to quite a number of other conversion functions, but I haven't looked into them.

**Comment by scivision** [comment]
Thanks, fixed in release 2.8.0 I think. Let me know if any more issues.
