### ISSUE TITLE
Add conversion from geodetic to geocentric spherical

### ISSUE THREAD

**Issue by leouieda** [geospace-code/pymap3d#54]
There is a function for converting latitudes from geodetic to geocentric but this is restricted to the surface of the ellipsoid. For many geophysical applications, we need to convert the `(latitude, height)` of points into `(latitude_spherical, radius)`. 

This is implemented in [Boule](https://www.fatiando.org/boule/v0.3.1) as [`boule.Ellipsoid.spherical_to_geodetic`](https://www.fatiando.org/boule/v0.3.1/api/generated/boule.Ellipsoid.html#boule.Ellipsoid.spherical_to_geodetic). Boule is more focused on gravity calculations than coordinate conversions so I'd be happy to move that implementation to pymap3d if it's of interest to you.

I can volunteer to do this given a bit of guidance as to where to put the functions and what they should be called to fit with pymap3d.

**Comment by leouieda** [comment]
👍🏾 sounds good to me! I'll give this a shot and open a PR soon.

**Comment by ryanpavlick** [comment]
geodetic2geocentric already takes height above the sphreoid in to
consideration:
https://github.com/geospace-code/pymap3d/blob/1ecb84ecf3f81980b845dbfd94dbfdaa08339359/src/pymap3d/latitude.py#L86
