### ISSUE TITLE
[Bug]: You should never call np.seterr()

### ISSUE THREAD

**Issue by sanguinariojoe** [geospace-code/pymap3d#79]
### What happened?

In [this commit](https://github.com/geospace-code/pymap3d/commit/dde1b9ccb0422805f6d3f4a791d8924ef308d11f) you added the line `np.seterr(all="raise")`, which is always called when importing pymap3d.

That is breaking many other packages running numpy (e.g. everyone computing the tale of a Gaussian distribution will find a nice surprise). On top of that, it is unnecessary, since you can catch warnings (see https://docs.python.org/3/library/warnings.html#testing-warnings)

**Comment by scivision** [comment]
Thank you. Working on this.

**Comment by sanguinariojoe** [comment]
TY! Really appreciated!

**Comment by sdhiscocks** [comment]
Looks like the *production* action failed, so this fix hasn't made it to PyPI yet.
