### ISSUE TITLE
publish release v3.0.1 failed

### ISSUE THREAD

**Issue by davidrigie** [geospace-code/pymap3d#81]
Action to publish release v3.0.1 to pypi failed. I think it's because this version string wasn't updated
https://github.com/geospace-code/pymap3d/blob/5802ca3670d74ecef9b348845e0c8d0a697ab8fc/src/pymap3d/__init__.py#L32

**Comment by davidrigie** [comment]
See:
https://github.com/geospace-code/pymap3d/actions/runs/4316701953/jobs/7532817227

Note it still says `3.0.0` in the build artifacts

**Comment by scivision** [comment]
Thanks!
