### ISSUE TITLE
[Bug]: ECI conversions give wrong result for sub-second dates (juliandate issue)

### ISSUE THREAD

**Issue by Pokornz** [geospace-code/pymap3d#84]
### What happened?

When trying to convert to/from ECI coordinates with dates that don't have whole seconds (i.e. milliseconds are not zero), the sub-second information is ignored in the Julian date conversion: https://github.com/geospace-code/pymap3d/blob/main/src/pymap3d/sidereal.py#L87
When used to for ex. convert satellite trajectories, the resulting trajectory has stair-like shape. 
![image](https://user-images.githubusercontent.com/33861443/235869647-5b2eecac-fc2f-4363-9ca5-89d89cb4711a.png)

**Comment by Pokornz** [comment]
It can be pretty much fixed by adding the microseconds
`C = (((time.second + time.microsecond / 1e6) / 60.0 + time.minute) / 60.0 + time.hour) / 24.0`
![image](https://user-images.githubusercontent.com/33861443/235871483-fb4d6b1e-40b1-47c8-aad5-95887b37b0d5.png)

**Comment by Pokornz** [comment]
I accidentally closed the issue. 
I have now submitted a pull request. It is my first time contributing to a code base, so any feedback is welcome.
@scivision does this change brake anything/ is there a reason why sub-second information is not used?

**Comment by scivision** [comment]
fixed by #85
