### ISSUE TITLE
[Bug]: vincenty.track2() Doesnt respect degree vs radian for vdist calculation

### ISSUE THREAD

**Issue by mcelhennyi** [geospace-code/pymap3d#90]
### What happened?

It appears to me after some testing that the initial `gcarclen` calculation of the `track2()` function respects the radian vs deg difference, however the [vdist()](https://github.com/geospace-code/pymap3d/blob/81172e221a4c9884450a38ec8a7ee382198cb7e3/src/pymap3d/vincenty.py#L536) function uses the input no matter what without conversion causing an issue when using radians for the lats/lons and `deg=False`.  Additionally it seems the later [vreckon ](https://github.com/geospace-code/pymap3d/blob/81172e221a4c9884450a38ec8a7ee382198cb7e3/src/pymap3d/vincenty.py#L544)and vdist calls also do no conversions. 

Is this the intended outcome?

**Comment by scivision** [comment]
vreckon() and vdist() do not have a "deg=" input. They assume the input is in degrees.

**Comment by scivision** [comment]
fixed by [343a786](https://github.com/geospace-code/pymap3d/commit/343a786f2de12164a4fc2dc0c2942e926ba77aaa)
